[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "musculus-base"
version = "0.0.1"
description = "Musculus, the Metadata Unification System."
readme = "README.md"
requires-python = ">=3.15"
license-files = ["LICENSE", "COPYING-RGB", "COPYING-W3C"]
authors = [
  {name = "Matthew Yu", email = "matthewyu0311@gmail.com" }
]
dependencies = []

[project.optional-dependencies]
test = ["jupyter", "ipywidgets"]

[tool.isort]
profile = "black"